### ISSUE TITLE
Using LogContext.SetPropertyName  to override ILogger scope values

### ISSUE THREAD

**Issue by shatl** [serilog/serilog-extensions-logging#120]
Hi,

the following code gives different results for Serilog logger and MS.Extensions.Logging within Asp.Net Core application

```csharp
using (LogContext.PushProperty("CorrelationId", "my-correlation-id"))
{
    Log.Information("test-serilog"); // Serilog logger
    _logger.LogInformation("test-ms-logging"); // MS Logger
    return await ProcessRequest(request, false).ConfigureAwait(false);
}
```

* when using Serilog logger,  value of `CorrelationId` will be `my-correlation-id`
* when using MS logger, value is overwritten with CorrelationId from the HostingLogScope (https://github.com/aspnet/Hosting/blob/master/src/Microsoft.AspNetCore.Hosting/Internal/HostingLoggerExtensions.cs)

Is this by design?

**Comment by nblumhardt** [comment]
(Reformatted your comment to show the first line of code.)

I think this comes down to the order in which the log context enrichment and the MEL enrichment are applied; I wouldn't call it "by design" but given there's not really any clearly-better way to implement it I think we could leave this as-is. Does it cause problems for you?

**Comment by nblumhardt** [comment]
Will close for now as "by design", although unintentionally, but let us know if there are problems around this - thanks!
