### ISSUE TITLE
Using in a netstandard 1.1 library project

### ISSUE THREAD

**Issue by uchitha** [serilog/serilog-extensions-logging#89]
Hi,

I'm developing a .net core library that needs to support .net framework 4.5 clients. So I've choosen .net standard 1.1 as the target platform.

I want to use Serilog as the provider for extensions logging. Serilog depends on netstandard 1.3 which prevents me from using it. However a client application on .net framework 4.5 can directly use it as it supports that.

I'm interested to know more about the underlying reasons for this dependancy on netstandard 1.3. 

Thanks.

**Comment by skomis-mm** [comment]
@uchitha underlying reason is that `netstandard1.3` have `AsyncLocal` type to implement ambient context which is used by `ILogger.BeginScope(..)`. `net45` target implements this differently with .NET Remoting API which isn't available in `netstandard1.1` since this target only contains a subset of `net45` API surface. 

So you need to multi-target your .net core library with `net45`/`netstandard1.3` targets in order to depend on this package.

**Comment by uchitha** [comment]
Thanks for the clarrification.
